-- =============================================================================
-- 0001_init_schema.sql
-- Yawn AI Agency — initial schema (Supabase / PostgreSQL)
-- -----------------------------------------------------------------------------
-- Creates the application tables that mirror server/schema.ts (the reference
-- Drizzle schema) plus the additional authentication columns and tables added
-- when real auth (email + Argon2id password, TOTP MFA, lockout) landed.
--
-- Design notes:
--   * All timestamps are TIMESTAMPTZ (store UTC, render per-client). The
--     reference Drizzle schema used `timestamp` (no tz); TIMESTAMPTZ is the
--     correct, defense-in-depth choice for an auth system.
--   * `id` columns use IDENTITY (GENERATED BY DEFAULT AS IDENTITY) — the modern
--     equivalent of Drizzle `serial`, while still allowing explicit IDs during
--     a data migration from the JSON store.
--   * Foreign keys cascade on delete so closing a user account removes their
--     data (aligns with the Data Retention Policy deletion procedure).
--   * This file ONLY builds structure. Row-Level Security, roles/grants, and
--     audit/retention are applied by 0002–0004 (apply in numeric order).
--
-- Idempotent where reasonable: IF NOT EXISTS / CREATE OR REPLACE / guarded
-- enum + policy-free DDL so re-running on a partially-applied DB is safe.
-- =============================================================================

-- Run everything against the `public` schema explicitly.
set search_path = public;

-- Useful extensions (Supabase ships these; create if missing). -----------------
-- pgcrypto gives us gen_random_uuid() / digest() for token hashing helpers.
create extension if not exists pgcrypto;
-- citext lets us store case-insensitive emails so UNIQUE(email) is robust.
create extension if not exists citext;

-- -----------------------------------------------------------------------------
-- Role enum (user / admin) — matches roleEnum in server/schema.ts.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'role') then
    create type public.role as enum ('user', 'admin');
  end if;
end
$$;

-- -----------------------------------------------------------------------------
-- updated_at trigger helper (shared by tables that track modifications).
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =============================================================================
-- users
-- =============================================================================
create table if not exists public.users (
  id                   bigint generated by default as identity primary key,
  open_id              varchar(64)  not null,
  name                 text,
  email                citext       check (email is null or position('@' in email) > 1),
  role                 public.role  not null default 'user',

  -- ── Authentication (added with real auth) ──
  -- Argon2id encoded hash ("$argon2id$..."). Empty string for legacy/demo users.
  password_hash        text         not null default '',
  mfa_enabled          boolean      not null default false,
  -- otplib base32 TOTP secret; NULL until MFA is enrolled. RESTRICTED data.
  mfa_secret           text,
  -- SHA-256 hashes of single-use MFA recovery codes (never store plaintext).
  mfa_recovery_hashes  text[]       not null default '{}',
  failed_attempts      integer      not null default 0 check (failed_attempts >= 0),
  -- Account is locked until this instant (NULL = not locked).
  locked_until         timestamptz,

  created_at           timestamptz  not null default now(),
  updated_at           timestamptz  not null default now(),
  last_signed_in       timestamptz  not null default now(),

  constraint users_open_id_unique unique (open_id),
  constraint users_email_unique   unique (email)
);

comment on table  public.users is 'Application end users. Auth columns hold RESTRICTED data (password_hash, mfa_secret, mfa_recovery_hashes) — service-role only, never exposed to clients.';
comment on column public.users.password_hash is 'Argon2id encoded hash. RESTRICTED.';
comment on column public.users.mfa_secret is 'TOTP base32 secret. RESTRICTED — never returned to clients.';
comment on column public.users.mfa_recovery_hashes is 'SHA-256 hashes of single-use recovery codes. RESTRICTED.';

create index if not exists users_email_idx        on public.users (email);
create index if not exists users_role_idx         on public.users (role);
create index if not exists users_created_at_idx   on public.users (created_at);
-- Partial index to quickly find currently-locked accounts during auth.
create index if not exists users_locked_until_idx on public.users (locked_until)
  where locked_until is not null;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.set_updated_at();

-- =============================================================================
-- image_generations
-- =============================================================================
create table if not exists public.image_generations (
  id          bigint generated by default as identity primary key,
  user_id     bigint        not null references public.users (id) on delete cascade,
  prompt      text          not null,
  image_url   varchar(2048),
  image_key   varchar(2048),
  metadata    jsonb         not null default '{}'::jsonb,
  created_at  timestamptz   not null default now()
);

comment on table public.image_generations is 'AI image generations owned by a user. CONFIDENTIAL data, RLS-scoped by user_id.';

create index if not exists image_generations_user_id_idx        on public.image_generations (user_id);
create index if not exists image_generations_created_at_idx     on public.image_generations (created_at);
-- Common access pattern: a user's latest generations first.
create index if not exists image_generations_user_created_idx   on public.image_generations (user_id, created_at desc);

-- =============================================================================
-- web_scrapes
-- =============================================================================
create table if not exists public.web_scrapes (
  id                        bigint generated by default as identity primary key,
  user_id                   bigint        not null references public.users (id) on delete cascade,
  url                       varchar(2048) not null,
  raw_content               text,
  markdown_summary          text,
  competitive_intelligence  jsonb         not null default '{}'::jsonb,
  automation_template       text,
  created_at                timestamptz   not null default now()
);

comment on table public.web_scrapes is 'Web scrape + competitive-intelligence results owned by a user. CONFIDENTIAL data, RLS-scoped by user_id. Subject to 12-month retention (configurable).';

create index if not exists web_scrapes_user_id_idx      on public.web_scrapes (user_id);
create index if not exists web_scrapes_created_at_idx   on public.web_scrapes (created_at);
create index if not exists web_scrapes_user_created_idx on public.web_scrapes (user_id, created_at desc);

-- =============================================================================
-- password_reset_tokens
-- -----------------------------------------------------------------------------
-- Stores only the HASH of a reset token (never the plaintext). The backend
-- emails the plaintext; lookups hash the presented token and compare.
-- Service-role only — no client/anon/authenticated access (see 0002 / 0003).
-- =============================================================================
create table if not exists public.password_reset_tokens (
  id          bigint generated by default as identity primary key,
  user_id     bigint       not null references public.users (id) on delete cascade,
  -- SHA-256 (or stronger) hex/base64 hash of the single-use token.
  token_hash  text         not null,
  expires_at  timestamptz  not null,
  used_at     timestamptz,
  created_at  timestamptz  not null default now(),

  constraint password_reset_tokens_token_hash_unique unique (token_hash)
);

comment on table public.password_reset_tokens is 'Hashed single-use password reset tokens. RESTRICTED — service-role only, no RLS policies granted to clients. Expired/used rows purged by retention job (0004).';

create index if not exists password_reset_tokens_user_id_idx    on public.password_reset_tokens (user_id);
create index if not exists password_reset_tokens_expires_at_idx on public.password_reset_tokens (expires_at);

-- =============================================================================
-- auth_audit_log
-- -----------------------------------------------------------------------------
-- Append-only security audit trail (logins, lockouts, MFA changes, role
-- changes, password resets, and DB-level row changes written by triggers in
-- 0004). Service-role only. Subject to 90-day retention (configurable).
-- =============================================================================
create table if not exists public.auth_audit_log (
  id            bigint generated by default as identity primary key,
  -- Nullable: the actor may be unauthenticated (e.g. failed login for unknown
  -- email) or the row may outlive the user (ON DELETE SET NULL keeps the trail).
  user_id       bigint       references public.users (id) on delete set null,
  -- e.g. 'login_success','login_failure','account_locked','mfa_enabled',
  -- 'password_reset_requested','role_changed','row_insert','row_update', ...
  event_type    text         not null,
  -- Table the event relates to when generated by a DB trigger (NULL otherwise).
  target_table  text,
  -- DB role / actor that performed the action (e.g. current_user / app GUC).
  actor         text,
  ip_address    inet,
  user_agent    text,
  -- Structured detail (old/new diffs from triggers, reason codes, etc.).
  detail        jsonb        not null default '{}'::jsonb,
  created_at    timestamptz  not null default now()
);

comment on table public.auth_audit_log is 'Append-only security audit log. RESTRICTED — service-role only. 90-day retention (configurable, 0004).';

create index if not exists auth_audit_log_user_id_idx     on public.auth_audit_log (user_id);
create index if not exists auth_audit_log_event_type_idx  on public.auth_audit_log (event_type);
create index if not exists auth_audit_log_created_at_idx  on public.auth_audit_log (created_at);

-- =============================================================================
-- End of 0001_init_schema.sql
-- =============================================================================
